import type { AppLanguage } from "../../library/types.js"

type Dict = Record<string, string>

const en: Dict = {
  appName: "Doorei",
  welcomeTitle: "Welcome to Doorei",
  welcomeBody:
    "A recall library for downloaded courses. Choose App language, then download the required models.",
  appLanguage: "App language",
  persian: "Persian",
  english: "English",
  requiredModels: "Required models",
  downloadModels: "Download models",
  downloading: "Downloading…",
  modelsReady: "All required models are on disk",
  providerOptional: "Provider (optional)",
  providerUrl: "OpenAI-compatible URL",
  providerKey: "Provider key",
  continue: "Open Library",
  gateHint: "The Library stays closed until language is chosen and every model file is downloaded.",
  newCourse: "New Course",
  courseName: "Course name",
  newSession: "New Session",
  sessionName: "Session name",
  optionalDate: "Date (optional)",
  addVideos: "Add Videos",
  addFolder: "Add folder",
  settings: "Settings",
  search: "Search",
  ask: "Ask",
  summary: "Summary",
  notes: "Notes",
  composerPlaceholder: "Write a Note…",
  timestamp: "Timestamp",
  noVideo: "Select a Video to play",
  fileMissing: "File missing",
  relink: "Relink",
  relinkFolder: "Folder moved…",
  deleteVideo: "Delete Video",
  watched: "Watched",
  next: "Next Video",
  regenerate: "Regenerate Caption",
  retry: "Retry",
  scopeVideo: "Video",
  scopeSession: "Session",
  scopeCourse: "Course",
  searchPlaceholder: "Search Captions and Notes",
  askPlaceholder: "Ask about this Video, Session, or Course",
  askOff: "Ask is off until a Provider is configured.",
  noSummary: "No Summary yet. Configure a Provider to generate one.",
  noNotes: "No Notes on this Video.",
  outputLanguage: "Output language",
  spokenDefault: "Default Spoken language",
  autoplay: "Autoplay next Video",
  confetti: "Confetti on Watched",
  subtitles: "Subtitles",
  speed: "Speed",
  improvePrompt: "Improve prompt",
  summaryPrompt: "Summary prompt",
  askPrompt: "Ask prompt",
  save: "Save",
  cancel: "Cancel",
  providerKind: "Provider kind",
  jobs: "Jobs",
  emptyLibrary: "Create a Course to start.",
  create: "Create",
  renameCourse: "Rename Course",
  editNote: "Edit Note",
  markWatchedAtEnd: "Mark Watched when a Video ends",
  fromFolder: "Original folder prefix",
  spokenLanguage: "Spoken language",
  providerOn: "Provider",
  providerOff: "No Provider",
  settingsPlayer: "Player",
  settingsLanguage: "Language",
  settingsProvider: "Provider",
  settingsPrompts: "Prompts",
  downloadLog: "Download"
}

const fa: Dict = {
  appName: "دوری",
  welcomeTitle: "به دوری خوش آمدید",
  welcomeBody:
    "کتابخانهٔ مرور برای دوره‌های دانلودشده. زبان برنامه را انتخاب کنید، سپس مدل‌های لازم را دانلود کنید.",
  appLanguage: "زبان برنامه",
  persian: "فارسی",
  english: "انگلیسی",
  requiredModels: "مدل‌های لازم",
  downloadModels: "دانلود مدل‌ها",
  downloading: "در حال دانلود…",
  modelsReady: "همهٔ مدل‌های لازم روی دیسک هستند",
  providerOptional: "ارائه‌دهنده (اختیاری)",
  providerUrl: "نشانی سازگار با OpenAI",
  providerKey: "کلید ارائه‌دهنده",
  continue: "ورود به کتابخانه",
  gateHint: "کتابخانه تا انتخاب زبان و دانلود کامل همهٔ فایل‌های مدل باز نمی‌شود.",
  newCourse: "دورهٔ تازه",
  courseName: "نام دوره",
  newSession: "نشست تازه",
  sessionName: "نام نشست",
  optionalDate: "تاریخ (اختیاری)",
  addVideos: "افزودن ویدیو",
  addFolder: "افزودن پوشه",
  settings: "تنظیمات",
  search: "جستجو",
  ask: "پرسش",
  summary: "خلاصه",
  notes: "یادداشت‌ها",
  composerPlaceholder: "یک یادداشت بنویسید…",
  timestamp: "زمان",
  noVideo: "یک ویدیو را برای پخش انتخاب کنید",
  fileMissing: "فایل پیدا نشد",
  relink: "اتصال دوباره",
  relinkFolder: "پوشه جابه‌جا شده…",
  deleteVideo: "حذف ویدیو",
  watched: "دیده‌شده",
  next: "ویدیوی بعدی",
  regenerate: "تولید دوبارهٔ کپشن",
  retry: "تلاش دوباره",
  scopeVideo: "ویدیو",
  scopeSession: "نشست",
  scopeCourse: "دوره",
  searchPlaceholder: "جستجو در کپشن و یادداشت",
  askPlaceholder: "از این ویدیو، نشست یا دوره بپرسید",
  askOff: "پرسش تا پیکربندی ارائه‌دهنده خاموش است.",
  noSummary: "خلاصه‌ای نیست. برای تولید، ارائه‌دهنده را تنظیم کنید.",
  noNotes: "یادداشتی روی این ویدیو نیست.",
  outputLanguage: "زبان خروجی",
  spokenDefault: "زبان گفتار پیش‌فرض",
  autoplay: "پخش خودکار ویدیوی بعدی",
  confetti: "شادی‌پاش هنگام دیده‌شده",
  subtitles: "زیرنویس",
  speed: "سرعت",
  improvePrompt: "دستور بهبود",
  summaryPrompt: "دستور خلاصه",
  askPrompt: "دستور پرسش",
  save: "ذخیره",
  cancel: "لغو",
  providerKind: "نوع ارائه‌دهنده",
  jobs: "کارها",
  emptyLibrary: "برای شروع یک دوره بسازید.",
  create: "بساز",
  renameCourse: "تغییر نام دوره",
  editNote: "ویرایش یادداشت",
  markWatchedAtEnd: "علامت دیده‌شده در پایان ویدیو",
  fromFolder: "پیشوند پوشهٔ قبلی",
  spokenLanguage: "زبان گفتار",
  providerOn: "ارائه‌دهنده",
  providerOff: "بدون ارائه‌دهنده",
  settingsPlayer: "پخش",
  settingsLanguage: "زبان",
  settingsProvider: "ارائه‌دهنده",
  settingsPrompts: "دستورها",
  downloadLog: "دانلود"
}

export function t(language: AppLanguage | null, key: keyof typeof en): string {
  const dict = (language ?? "fa") === "fa" ? fa : en
  return dict[key] ?? en[key]
}
